import AdminLayout from "@/app/_components/dashboard/UI/AdminLayout";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Welcome to Admin Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AdminLayout>
      {children}
      <Toaster position="top-center" />
    </AdminLayout>
  );
}
