import AdminStyleProvider from "@/app/_components/provider/AdminStyleProvider";
import ReactQueryProvider from "@/app/_components/provider/ReactQueryProvider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Welcome to Admin Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <AdminStyleProvider>
            <ReactQueryProvider>{children}</ReactQueryProvider>
            <Toaster position="top-center" />
          </AdminStyleProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
